language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - secure: c7okWKLXjb3GTKIuigJ+YeJAnoZeNDw2MHp/C0Yf0XzjtcS2RkntQEQDb7oRCfhgKMQ0gmQA82AnFYiBn14mmwf8IBW+Fqe5EcDewsMLXdFPKlq+Gr2dPEW2cGoekKTe81XaCgfGrIc/QA5JJMriy5PFgf5U6zn1ccfRzUNpbjv01E80UpJ+krLasGX1RNH6FudiHdEtAqTVXkzp/J7apQK3NXKXwNxLuJipGREpdtIh4jeUWlWC5gurGTiMMzlQMFg44XzNW853OmYiIv6jKZU6usRiFXsyGE546pPzRMYLlUxF+pg9oTK+cot+BQhoZ6RNKuRvG7wBHegwryvb1gpKmhOyPRiDNgHA3d7aV578f+I/s16WObN0m1zrGKf3uyY7dxz1X7/+nmXkDl64ohJgs8TkNOEemURPcs1/Chgd/z6NR9CcVsHuT5mGXK5G5RqxZmGPpeLzLVEtMVdj9h8XCbRBKDnWciWG56WkVEOd3YH1QqzOXd1RtTJW/Aq+ZNsS7my6yt53qx+41dzlBGblqW7O8DXppOT+UYMp381kWG/qYEXqj+Wca6WOAPNiI63B87A4Bx6RUQYfX5q2y0RILybjjOjAPV09Qy4TYco1ae4dL61gd6Pd/ANNHJxwU5PxxM4RMbed9H1rLUwnZBNijJ2FnO7YbstqC6F2J2Q=
  - secure: IE4IQtMPqHaR9SE+O7Wp97iwtWIlhkA6O0BgPqwQ+qsTGqdNmMCPk2h8LYkN84dNIABqKiocjh2cRpTI05piw30976rNFAFGaFm1cWPC2o//CLFweOr6xXaPmGO4t79pLteTx1CFPyr5Wq/kXDwfQibEL63TqtFkUTHbspAPm7Dab7df8AsX26AP6H4epStlpYRI48SgswQ+jnegTHuv4sv0UGNpjmktZ+yoX9AcwX27bTbnFoP7QO159/GGmdOSGX1tixo5tSoFhINuoyiClPi0jbFHjhazJD+SYM0Tsh1NlfgGfUslDmU4tER3of/1/2RDNft2tMlwk78P9lru4aPmaCQVXwACHtsGnGS8p+bfYNdVmPHnmkpLbERvZ6yegQwBIkhZzSvAp5kiai08I8UqZ2vYLq7fG/cOlP5rK/EbpGoQaXaLUrcMQbniExAzJb3j9v4Xuv4lSOG6O66gMoW9o+BK3mJMNooZha2xDI1EVkiWNSE/DfWhvjeXsnurGUG1ZGOdYUN8k4B2ChF8v+lNwcohwHxBxlPv9+P1CKZPw5B6sFtlQv0FaM27ZZeUA1ZJ6CkoFPOvW6FWr64oql126EsgY2+1uUI979owiSVO5zYt5VPld1JbY/hLBFQ09VHYySHwmC0+u3roWjHpNnsl+wPVL/RMSoH56k2+/Hc=
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements-build.txt
script:
- python ./exrb-local test
jobs:
  include:
  - stage: deploy
    python: 3.6
    script: python ./exrb-local pypi
