language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
    - secure: Vd7lE4bjnZcaB8gD/Ck7dPyfZEZ1+/eaA3tMP+4/IYzDRCLImGnEsgHA72cVabwKLLLyUoi+di7FUWdlBvU+yPT9X8viyNCVeFRc5ppXzbpfSnkQs+ZI9c52UDLyjEWb9LXGSBX0OL/s7gBBOP5NqWd5o18yq+7qmeU7ZwJZ+eNPv9HikNwWUcZ289c0M6agmVHCv32m8UjqXGPX0tqMdusDDBqeRob8leIvQKTGrf3mYjACKfQ/dBsB5waMPyx+GkiWkpc6pkQv3er+T8hDPm9te/H0bXgq55lKW43Irz1db8co0//RBaApert1zjHDTqX62cCrxkJpPtD5EWs/drUXmxt0tEAi1gPnXeVtci7X0mWzJ7vJrjUJRalHu4z2Tvw+lNnHSK4yXsgoyjverGKzoPoLbk+HSLuz85/AJf0k6RPqaF3Y3fKr4e8QK16x3Xu2bbZHiq8FB/4/v131fgIHTfmDrWMsD3dsuAhRCr0SUP/tTwchkV4ahQ6/djnSanHfwKUKmU8bMqUzVJk0QG85mria0iW1l1SNmn/HHF/6EYHRCCSXW20SC47TJX1US/oUWLobB52DpnKvqLpGxcqEYSRjlezORrjaqbxyZ3bdtPDYQBs7Rb8cvQFDzQ6hG2ckZbzlo526AyYMe1T1bucANGtby0fwtg+FhsYv74s=
    - secure: 2hIZbKxQ25bgdXsVvLKFryaAfzoHmbUABiK4iwj4PTANl8fDnE1i4/z1y8rwwWQgVsyhsJbWPS2APRi9QHLHJqfGNTkqMMU8n6Vcs8ri2ijNTEsIR/hq5BhZLJkKumpZWYDYvSonFaiTx4KKB3gpw2J9mfpXIhqhMyOzCjwhOdtZnu4VmMb/i1w9NeUdxV5S91vYZ08VsNZoAxoDjE7mz3YMQlZ+tqW04X+t7lwROQPxx2AP6nzL7mUiMG3ZuIKLBamDQ2hAdxoBQd4RMQ8Ni5+1qUByN5ATKUJ7qghBXNFlNdqJQ4Y6tZm7py2eID9H+Ds4Z92WS/R3IVHFgV3ipZdP8vMaH0OQtUvxlTAc17UuLJBBCr5kSWg5P73eg9EpOMz9N2TjNH7hItnfpBxPSn86kSVIJ3KZVbn+4RQFloEp+VFlmizgpKRrD9+e/jdxRRCz7x2hFivHu8XPd0HUBQIBOzhjz/h18K8ruCcl0BPNUKhtwkZfuzQWpM/JAN6BxypUsmACBZvVN2iFzZeoD4ud5XmAbhkIeuj1gmxD1MjW5bJ9i4fueFNn0FBLtHmUcekAb9Sf+DmM4yfxnA9uZHhO1s51NxfkIoGiP4GTIieWSuViUEMhuXOxR7mSc/CH+Mw+noMP9mBtHOBF7cQjylA34FDhlaLa/Ujx07EyZmc=

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-build.txt

script:
  - python ./exrb-local test

jobs:
  include:
    - stage: deploy
      python: 3.6
      script: python ./exrb-local pypi
