language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - secure: IuORUUq/ZhPQxIHqDDUwEZg6eo3UpX5bS2+9Sv3FY9iPwnlaNzplKDaHo9enWzJjjtDHVC8hTMDelZzit6WbJMKbDeGqkDDb+pC1+6Adn4YICUcBo39itocUxAKbZ3/oCHR2audKZO6QhBETj5ZJHSCAeinP1JjCEXIU3mlc1ZNxiEKLlmuQUYxp+XOxcU9g2W4pGzR2C4DxOJQvewXW67onGcB7BuAlW0NLBVFrDWh1WinoCQgiWgCqmV4BczxhUJYTF4QB8cLFkx1zhAAcE29Ylh9pxw9bLMpKcL5BgHzCQUycvMDc8JVwLLc6qGOYkcTDBqu9IINhNSkfJ4iTGJOVQbk+Rpt61HOjgEltR7zn7py5emkcTW6bob3LkJHFHP/JH6AumLUDfp6DVOGogNHGQ5bg8s2tsBu4mQlzst4S+86NsRXI5ZxFlODHGhBcBJcMOSZAWrOPPt7rjRNNdlTxrh21nIv77COEddmlaSTLKz88L0xN7aqLo09bPl5e+B70954EYcx45RnGDVRX852J+i1P+8hdsGO/3belQyMorXRj7eLNqit5i2eKO++DN2LegmWimgfPxTYidk809oXh93d/63pJBZb/plthhZ1aYlL/vNJsfsf/6dboSnOApCu3yydo+Q+8lDQuNrgTehf09M592P7A/M2QHh1XitI=
  - secure: Gbe+VHvxdd0nZ/b4K1sL7+gpSZCPEPLYdTviKlHZFf+h5RiAnPFfmSE5FSl/4drRHsazDqYsSdr+JIXLQmiYF2FyaRIDtxIP11bGn8eMy+twanf8XbWxdHP7va4L9tV1rUDg7L6PbWmD2HVO9fYQpzdM0naA8/y9q3ga6xgXY5RdvxcwqB+QEo8CyL/8YfZZHi490W9ZTZLenJDfOEsL8aw1gskDBnVU7mN8EEIEYF2cifvoldtSeb+I6PjwS9e2wSZkljt8vOMwtXiuu5dILBT8WOQJYd0EA4hmt1Z5AvhfrvHIkcnDMVARflY1lnttDxEecxEcg7ma2Bbu8gk+JMFh47uELtmLJpRwp3jrhR2QYva2pb04mb6mIC9i1XuVo8lZBNJL/kmpmOJCTo6c4mneQWtpkdETCeRQRy0uRehOFyJ7nv0sXCy4o8/hnu71NHUXVx/818H2PoyM9UofbmoN7wv3zvQhoZW1OzFOrf/gtrFd8nqFH7yj2XJggFwBcxWrNu2aO40CtjTWA04AHKGEdBtzaoxhLXrpXTvnz3d5Q2eWN5wMzUtrUObWcy206ScVHNB6cc5Ep/z2lF3vJmPn6679WE1fqvrwnwlQ70ZvfweMbluiB0faYK61GPLvHcsucRlrIxkFoMXmwvSG+/+g4JzktWecURmJfkHvjtQ=
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements-build.txt
script:
- python ./exrb-local test
jobs:
  include:
  - stage: deploy
    python: 3.6
    script: python ./exrb-local pypi
