language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
  - secure: ef06ilto0/NWmy1LZFB1NP9wHKa3mv4/AVD7lAv+sIxb/q/5AFpbg2nRpNNLycQU3a2Gfu/XTJ65gWim/+0eKffoF3Y3PkP5gGxJtsAAV+xYb/g+7h9JSWRyhbJg/7JNIFGVCmAnlgP7dzcr2hdQPsZyzQkV1IxbJHW8sTYyDfui2dRbyzIMgENV27A4JfI4pPcYC7vbC7P/cUvxgjE8MjUFh8ypnBBaVDEycfvZZUPT32Dig5SLYhsGBhyZhnVkGvO/YjITqJuMb0jADDeqhLMnIk/E4UyXzkFKS8C5qgIMhaXwbu5XqE8po9OopAf2nih40/sQvIonpWP2aIrZaM7a751XpBtUbsEvFmqrSSLQGxVYobIxJBEy4qZ4TZD9npiV/HgByyzhZ6o4XMrZYa65U72zp2CvGdN6YHpdt8NokUYFvHx8TWo85iNJRumiQBUJYldqLhehTVt4YRHiMp9nfNkkdLlXApx65MSeUPeRwIgwpHonBpCy4pNaAlBc8+pVw9hTScJiNMvDzdCiIiHspa3SL769r8SgfrD8FiLbBffF+n154/Ndo16JB1BlMuRTZvRYfXV8sp9Llq9UYBHpl+YS737RvGqp0xmq/Bs3E3phSHQEwXkbxTjK7+Oh4GcXU+AtLpp5TiN6MguUVVgR6sRbv6w8ydkvm7W7ObI=
  - secure: Yl95Z5p1oyRWyWkQpWDS9S314TZamJzCZp7MB2KxIrq7cuzeBXw180wj9av65vbUwMO/cG2Bb8yznTGjP0QDQEZ4VP5mcLFMuQwSHLw69VTeslnQd2Dz0snZK0Omg5m0n0Dstyzl89oqimx5Z/VZ4pajsFKqfF9LGEi+gDKBD9SmkrI8DRhDJtuqKxBmplFYc0u7yTDC+zBLepImpGMQ46SRRvzb/QTKTNCUwPi3j4W42NUokRkcKbWktZKnkCreZ6Qh/aF02DYZfWyYdraATXPaosSxTvKsdIdjasMc8MNmAhiPikK3qdgaocWTx4Z3/KrypoPNVl7EogAeXTHV08V0SDxvVJFJ1sF3/yfKUQJfmb2sXHfugHbZwnjwO7ub74dBHWGyKnoHNVQmNB2eKa4W9n3/VAh6wwLpBkAdo6x7n6UbD3PLnlZpSY6MTe53ND2H+1a/XjsYUwKkuw6VCYlRPp5W523x+cJCyfVYsUi43rD7KEdiTz2LaSYhnD9ltl7GaEDMdeFnLbH8Acqw7QKeE51gUtpv1RZaigfl/rJtpVbUbwRVW4TOa9OBhiHmnmhvP3f3IKhohambx1qxANdZFRZJAWz/LZMFAf7G+2CI7vTfu1ZyP1JkQMyr8KzgRFYsMzhuDtdxIDXTnEeqM+ZFNqp7BGZ3CJwbPPhQZ+I=

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-build.txt

script:
  - python ./exrb-local test

jobs:
  include:
    - stage: deploy
      python: 3.6
      script: python ./exrb-local pypi
