language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
  - secure: ujf9d8z3BvRXarBM6acOSxfA2X9Kn4m/ShMwxBD8ktRKQ5qJAehG04/gqiMrQaw/5vUTsaxNNPjcy62H8ruJPoY3IIa8MihcWVed4YcvsQrvCFOcS1NxzGO0EgGa/ID3L0DEDPIw6StVDfjPymUQCtPCOooliMqMplz0Y8XiqHSqyRB7jDfobxCT4I/Gx5lv7XzAlNSODWsO+9AzrLXWSkmoq3eSwe7kf3D519JBXOAAj1WhO2b8S6PyAycQ+0TrGZ7hq+iAmiFRr3nif1QO4G6E/yc6qDtQv8c3bAVbD9mVx4e0jOSF4HQypuTc1gMioQd/jJHKScxSRJ7cNSW8zzdl2Xwngyv7PtPQFuOFYutE4BXr4pdbKGgD8bqr1Crjlh7Iwf++L2yJ5VuZsmQIpFB7pR/qyTmVLHCoQ3ZWWMh94kpIULpUnphcCs21SWvgUzeg6GzYv7GXCOrWm67E5caPXBUfFRQ85XRB7BmCzDYP7JYBC0DjJ0dm+zrhnQwh52VTJEbPd/JddMqXNBzfVhzeKfQ2LN57FrOFX2DiJY7G2V+eHgrtelJDM2ThapXIpcR18HWkoWETvJ0S6KybMWGw4aZE1Myenaih/5zKt6McQ1nSL5fp/eOpw9/Du0FtWOhQjrTfLRu/TDOKJIMkvh6ask15LnFWsDd2I20dCL4=
  - secure: jmRshevX/TwYjFyKSrVf2vTzsIx0BUku2jaI6G58PqR9d7xV/7iZGRCkkR40VEvloZcUqwnPC+7VEkuvg6CBU2t2UntVQJhkl7wMd4LTXs+JHb0BpXDEYwgbZ/0yNgvpqpiD3fyXWWPNwNNDTt2kVioHfKdthiYaEEQXemxRRmjya7nZZ8M7VSGAlYycUvzU/ned/mquXWHRHIr/4a4t7A2bB+LeZICYr1+mh954oI7qk358GmD2M4OWnBkJ801coFitqRRfaoSsOiI8KQ0G5qqSERHqEnEATDF0f554hYuD0YgOIhkIbizq/dXYgkk4GYJGwE36Y1yvLKDhEoXkBbbrgtrwLdjYYOUJ97I+CQMJzDGAsYqICTK2R0tvtFML40Y7o9b+0d059CX8h/bg0vkcMioPSOmcIC69yVRa0qkHIMDUNl4hg4ulWXvRM1YfbXyzxvfM+C3amLkneyFjvnHR1OvjY2Y4nAMBPOyznDQjSTwsBiv6FQBBlgHbLJwF03k8Jy6UK4toUJavGnnpuLkC/D+gs78ZBLQWPhclpJYii0B2TRwTAg9gVj60hHhrF+tvoXLBz0pHM8AKDmJTsQnjlL/DysxCF8QkNcaZYjc//cGLy2PoHbYTmCtFAo4qMTa9jSXx0oGmniJnV4sZcomN2WJizQC4JcJopi68VHw=
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-build.txt

script:
  - python ./exrb-local test

jobs:
  include:
  - stage: deploy
    python: 3.6
    script: python ./exrb-local pypi
