language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
  - secure: Wksh7RNyabWWny2kFjsKVmWBIFZ77uel5+P1wlEN2QYaHRwHezdxpEHhwOrZnPR+y+z1Tl6eVxH1H8yTxeMmzzsDWeH8t4OkqWh3GobTNhH1pGsU6jnrln4c07Sm59H93vQWJyZpyeAGz07k+eqG+LEJ7tpimYrrLDTNSlsdMO7+Hd3J+9+B91THLybX/PnVv0P9UTBA1duBMzLmo2xTfsa87uASYI7V1vmP8FNQ1l0gFBD7//1L5Tt70nTHi6rzDpyQNKgSAKRZF3u4oPYEclVN9iWhsZbUZchYuHCxJQhFMLtwiaikow7WPENwUI5NjXYYol5eBa7+PFjS/cHSGPAbwQ/xN4dVTMNX4qkXjAtmWSbOTgcSoNAQdZHBu5yw4/ng75qxDLNSGEdjD4ouRJgU57X2RkL4siWPalZ71SVgN4/V2HYxFcskRPQRM30f2V5g/PaXrJSevYHEOXW08XxeRxnnwvH4TtWzVtA7cTBcys+lz4BsY48jv9GpH7jTLfNjrGlycJWZnY4GHzAjW9e1ZQETB08iX0yXNEuD6NOr4a1EeNkpQlHl2e9dM4mHiAgaCss8g9kOXo3eJSsT3Te+QtQERRXCibY5Qf50lIZj/ewXNiOL2FwQFVeHtTCy9tvsbhG9w6QFxAvwtByFbaoZJ8YlUtakamrsB6Zu4Mw=
  - secure: uLBA+zmKbjLVV1a3SqtLbfgNJ3degzfOrLNe0En24qYHjP/1ULc+x3s/JPTWGtPT1+S8Wnn2WExJyMyIhUEt6akBxZ6f/MoLrkEZBU6lsSJ5IKMRD/aJEILHqz80wTJIDp58A3jtSKd28AYrlR7R08iK6dIRC0Gag51a7NDoNIcmx2hjN92CikvYF1giE/MPV4VWzztICsHwaBJeHc+3qvxbMkWVGUP+xmL5FuyeXFLdNsJXZbimiT8k47tYUOHY1laSrnPjLhmaWaG88gL9Poa7n1JQIrPNZyG/SCHnOIsYMAzss2bTsG6cbDXppDf3cOJwOXoKciZYBUpL/GWnp2LE0oGopXz2NXgDsrir0GfCw75C61Bbo++/tVX/Cicf3quKpONfjuxjO6PmBV8VV/7ifbgDQyg25eSWcSwbpL2U4CpquMaumJZCKO+3NqQMz3LfMndFv27D3yUNtcut4YaG7KqKXiMLAG4NQFCi0JvhXvTeqFuDM2lcXmvXbJ+u54qQD0XAn7tnx5P1iGb/nL0FTvnxdExJ/+2z5cM6ULARRiUu6i7oZqvUDSHVENNKOAO3dajuddODvCB+wb17YTPDnsfnDuCtzbF4/97EmhggFaqJOltSffu0S36Ul5RVB/RrayCeGZ1codp3DbzPu9MSJY9EE/vQ8SNhL+3cV2c=

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-build.txt

script:
  - python ./exrb-local test

jobs:
  include:
  - stage: deploy
    python: 3.6
    script: python ./exrb-local pypi
