language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
  - TWINE_USERNAME=exr
  - secure: CCMBGE/ABaeXKm4Dnec4IeF/45Q+JZB2xhwfnyXANxH9bXx+rkcqWLx/dEnCivg4GZ15kMyRE69ww9XvfDZgSygqU4Axl5Q26tq4C0OXO2sfhNUVIgeXTJC0KPBVmVvWhabKCgY2PTsyfpN80Z8xrzQlrYoc9uwAYfSJHjYpLXL1UiSP44dgqENj6yr04v0mHTvCbuAHu+nxpBSYducAL92zaazdivjEF0OXPNn/LCNnIXXhJDo1Sx6314F4WLMbpV8ii7+p4ylcq/XlE5pHOx4hdvIQztjg6l2vJ1ajxV4UTLlhmiznbK06+vfo+kJ0lRw/Q3E2x2q8fF1CjA3fMlwA+ViqIKRmsJz7Mnp/V+rwk3jEmhdJ9WqTFyzqU5MhF6SkrkbiuJMJD6vYmkhtP/9bDKGCgm2fBauU9FJRuLbITJSydSWF/WVsh4BQ8xGzcyVPK7T0+YZzoinpomra3LPEzqx8apvv5RyO4Qo9o4v2bPMvMfkdkOkLUc9mLZJFaXa11hH2qZmifw10R2WcQ4SJsO9/n5DJi7LKRz9XyYDwZVAdCFTJ/FAwkPkinIUD53DvnVXnt4HaJXQDWRwzk3aZF/gFozVlFDqzTtMZcJ8Q/3WPL9p9sFzKAGR4yOtNOhDDeURRXlrtM3/mgySi9XsBk2tfWRO6zjQFnOkUyy4=

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-build.txt

script:
  - python ./exrb-local test

jobs:
  include:
    - stage: deploy
      python: 3.6
      script: python ./exrb-local pypi
