language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - secure: ALXHw6yl3XBhIwMuazVlSVrXMTT2o1T/x2j3IYF9t0yTUufeXjiJa3oe7rWbhR67jZGynq+NAxIeuBU2/ZAztzLK6nOc7G50QpvLF2HSniGLS+4bmGoN+eZTXYcDIIRIxNMzIOg481J5GNq71kYOtvZ+pn5dL22vOij2/DNw9csaZzWp7uzQG0WgIqAlj5SSDgdX8/1XZe6JFldL+cl4uxGW3xM8jv8cLTer7xf9/OfPcYuhZTcVXat+yaZmAldnSP6ANQ0xapg0pxKfLivmDIYNwZhlLvyHuJgQGlyRP+gwCPkmdvdDB466QAToeY8hhPJgk0VPH7Nepy5ZZveGIBqZJbcKO45snMsSDyUkvthUuvOainm6pUqTBSwiUndiAy6Wu9OdlvdU+S7mFutDR0EIR6hY475lzNTeTgRW7VLF5BfV51PGyR3Tw+94Rg0A1eSqxyx1Ul+2uGx+LshDRCKTeWKp+6NyUZCfQ6S2VlMdw9KsSzLKGlqW1WlCGqkMzaa8Ksp5mzxXfmjsXHwFtlySVMiimWK4VnGbVpJPA8cSpzhpAmcIqWlyjIyJTYc+dz0UH5Z8llLLHqoHWLGihLahWuF2U0iaBdW5Ay+Bg2t34xBeHiOR8HPEGvqn3fqZ4Vdqmm9icq5W5VPZvc1bSFLvwvNDBwxsV7Rb2KqLUFs=
  - secure: CWqlltUYbQABUlaGNY5Q2nGoKGrrzB/eO7Pn0vB9QQoSiE9oIDDoh8EcnMaegmDR2hMdR2k6OdEDFS92/K3XcpKHIrFxoY+pw4HOmGo5PR6S6cF8nwRljI/vksOY842oxSNZTH3bA7OfPuxCMdhlElIo0YGZx2AjhI/M3vUUIdrcD0BWKSPEr8+ZmWehKC1cGN21aMKTC25FNkietKHUoUvu2oVUNDmC2fPSYNgtVNnETUqtleX6G4bEpYK5Jpw92Q0DmhoJp2YzIN6BybNUmZvyyMcgGsGW4Gj5vAyq3iZuW/vkPa0LgPe3ICgwvUUq2QmpLj11VeZ32DzyBhgdf8FLMlJdNqh2K2fn4rYTmhWq4SJ18t3DdZlY139XN6HXnhOv3x4QC2rlggZwEiuQSrGvOWiKS7sbigeS1XNjr9X2WBnnqp0bLSdMZC5L9iM2Fo8GvOuFI9sGZUzI18b0ZQouWvH6R4D5GzxOFeTC59ywYIAR3QJx1VvZNkU8IOs4ozHIPA+thPBEAwMNMLfp4xyz3prcUxJiwuOVcZ7nO2mU/EMjZLjgj5KvXJKhHYToFcMiI3sRGP0IxUbNsG0aNTXEwKlbw1Ht67/wdUp8o03Gr9HqfOeuoCM+F6w3pr+7oODd7+7q19sJ1kLKYP7mm7k/6L8zEvrWL+xwgBMXAes=
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements-build.txt
script:
- python ./exrb-local test
jobs:
  include:
  - stage: deploy
    python: 3.6
    script: python ./exrb-local pypi
